---
format: html
---

**References**

[Stat 218 Syllabus](stat218-syllabus-f26.qmd)

The textbook (and related resources) can be found on Canvas under Wiley Course Resources.

Simulation applets for our book can be found here: <http://www.isi-stats.com/isi2nd/applets2021.html>

---

**Chapter P**

- [Slides](notes/ch0/Notes218_Chapter_P.qmd)
- [Data types activity](notes/ch0/data-types-activity.qmd)
- [Practice problems](notes/ch0/example-problems.pdf)

**Chapter 1**

- [Handout](notes/ch1/Notes218_Chapter_1.qmd)
- [Never accept the null](notes/ch1/never-accept-the-null.pdf)
- [Your turn!](notes/ch1/in-class-exercise.qmd)
- [Exploration](notes/ch1/Exploration1-4.pdf)

**Chapter 2**

- [Handout](notes/ch2/ch2-notes.pdf) | [Instructor copy](notes/ch2/ch2-notes-instructor-copy.pdf)
- [Example problem](notes/ch2/in-class-practice.pdf) (not graded)
- [Your turn!](notes/ch2/in-class-exercise.qmd)

**Chapter 3**

- [Handout](notes/ch3/ch3-notes.docx)

    - [Notes from Tuesday](notes/ch3/ch3-notes-inclass.pdf)

- [In-class problems](notes/ch3/Chapter 3 Problems.docx)

**Chapter 4**

**Chapter 5**

**Chapter 6**

**Chapter 7**

**Chapter 10**