---
format: 
  pdf: 
    include-in-header:
      text: |
        \usepackage{fancyhdr}
        \pagestyle{fancy}
        \fancyhf{}
        \lhead{STAT 218}
        \chead{Chapter 3}
        \rhead{Fall 2026}
        \rfoot{\thepage}
        \setlength{\headheight}{14pt}
    fig-align: center
---

# Section 3.1 Confidence Intervals

Up until now, we have been using hypothesis tests to determine if a value for a parameter is plausible. Our new goal is **estimation**: what values of the parameter are plausible?

**Confidence Interval:** a range of likely values for the \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_



## Example: Legalization of Medical Marijuana

In February of 2014, a Star Tribune Minnesota poll asked a random sample of adults in Minnesota, "Do you support or oppose legalizing marijuana for medical purposes in Minnesota?" Of the 800 adults surveyed, 408 (51%) answered that they would support this. Ultimately, the Star Tribune conducted this poll because they wanted to estimate the proportion of adults in Minnesota that felt (at the time of the survey) that medical marijuana should be legalized. Keep this in mind as you answer the following questions.

Source: <http://www.startribune.com/politics/statelocal/245910931.html>

Answer the following questions:

1)  What is the population of interest?


\
\
\



2)  What is the parameter of interest?

\
\
\


3)  What is the sample?

\
\
\


4)  What is the observed statistic of interest? This is also called a **point estimation.**

\
\
\


5)  What would happen if you took a different sample of 800 Minnesota adults?

\
\
\


Hypothesis

> Null: The long run proportion of Minnesotans who feel medical marijuana should be legalized is equal to \_\_\_\_\_.
>
> In symbols: $H_{0}:\pi =$
>
> Alternative: The long run proportion of Minnesotans who feel medical marijuana should be legalized is different from \_\_\_\_\_.
>
> In symbols: $H_{A}:\pi \neq$

Calculate the p-value from the **Theory Based Inference Applet.** Note: when setting up the applet, you either enter the number of successes into the "count" box or the point estimation into "sample $\widehat{p}$". The other box will automatically fill in.

6)  Based off the p-value, would you Reject (R) or Fail to Reject (FTR) at a significance level of 0.05?

\
\
\

The general idea behind constructing a confidence interval is that we can use our sample to provide a plausible range of parameter values. Using the Theory Based Inference applet, change the values of $\pi$ to fill in the following table. (i.e., change the hypothesis test for different parameter values while using the same sample)

  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
      $\pi$                                     0.45                                           0.46                     0.47                     0.48                     0.49                     0.50                     0.51                     0.52                                0.53                                0.54                     0.55
  --------- -------------------------------------------------------------------- ------------------------ ------------------------ ------------------------ ------------------------ ------------------------ ------------------------ ------------------------ ---------------------------------------------- ------------------------ ------------------------
   p-value                                 

    R/FTR                                                                                                    
  --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------



7)  What trends do we see?


\
\
\

8)  When we Fail to Reject, are we saying the null or alternative is plausible?

\
\
\

9)  What is the interval of plausible values?

\
\
\


**Interpretation:** We are 95% confident that the long-run proportion of Minnesotans who feel that medical marijuana should be legalized is between \_\_\_\_\_ and \_\_\_\_\_.

## General Form of a Confidence Interval

Notice how the confidence interval is centered around the point estimate.



$$\text{Confidence Interval (CI)}=\text{Point Estimate}\ \mathbf{\pm}\ \text{Margin of Error}$$

In the previous example, the confidence interval can be expressed as:

51% $\pm$ 3.5% (i.e., 47.5% $\leq$ $\pi$ $\leq$ 54.5%).



## Significance Levels ($\alpha$)

Significance Level + Confidence Level = 100%

When $\alpha = 0.10$,

- Relates to a 90% CI

- Rejects when p-value \< 0.10

- Narrower than 95% CI

- Rejects the null more often (remember than $\alpha = 0.10$ means that we reject the null 10 percent of the time)





When $\alpha = 0.05$,

- Relates to a 95% CI

- Rejects when p-value \< 0.05

When $\alpha = 0.01$,

- Relates to a 99% CI

- Rejects when p-value \< 0.01

- Wider than 95% CI

- Rejects the null less often than 95% CI

Using the 95% confidence interval as a reference, draw what you would expect from the 90% confidence interval and 99% confidence interval

95% CI

  ----- ------ ------ ------ ------

  ----- ------ ------ ------ ------

90% CI

  ----- ------ ------ ------ ------

  ----- ------ ------ ------ ------



99% CI

  ----- ------ ------ ------ ------

  ----- ------ ------ ------ ------



## Technical Note About Confidence Intervals

We say that we are "$(1-\alpha)100\%$ confident" because $(1-\alpha)100\%$ of the confidence intervals generated from samples of a given population will cover the true parameter value. In the instance of $\alpha = 0.05$, this means that 95% of confidence intervals generated from samples within a population will cover the true parameter value. In Section 3.3, we will look at an applet that will demonstrate what this means. This is NOT the same as saying that the probability of the parameter being in the confidence interval is $(1-\alpha)100\%$



# Section 3.2: Confidence Intervals for One Proportion

## Formula

The general formula for confidence intervals is as follows:

$$\text{Observed Statistic} \pm \text{Multiplier} \cdot \text{Standard Error}$$



Unlike in Chapter 1, we now have a new formula for the standard error:



$$SE = \sqrt{\frac{\widehat{p} \cdot \left( 1 - \widehat{p} \right)}{n}}$$

Notice how we are no longer using $\pi$ in the calculation, but rather $\widehat{p}$.

To construct a 95% Confidence interval, the multiplier we will use in this course is 2. This gives us the confidence interval for one proportions to be:



$$\mathbf{CI =}\widehat{\mathbf{p\ }}\mathbf{\pm 2*\ }\sqrt{\frac{\widehat{\mathbf{p}}\mathbf{*}\left( \mathbf{1 -}\widehat{\mathbf{p}} \right)}{\mathbf{n}}}\mathbf{= (Lower\ Limit,\ Upper\ Limit)}$$

Technical aside: if you look into confidence intervals from sources outside of our class, you will notice that the multiplier value for a 95% confidence interval will likely be 1.96. However, we will [only use a multiplier value of 2 for this course.]{.underline}

## Example: Legalization of Medical Marijuana

Recall the medical marijuana survey question from Section 3.1. Calculate the 95% confidence interval.

In February of 2014, a Star Tribune Minnesota poll asked a random sample of adults in Minnesota, "Do you support or oppose legalizing marijuana for medical purposes in Minnesota?" Of the 800 adults surveyed, 408 (51%) answered that they would support this.



> $$\widehat{p} =$$
>
> 
>
> $$n =$$
>
> 
>
> $$SE = \sqrt{\frac{\widehat{p}*\left( 1 - \widehat{p} \right)}{n}} =$$
>
> 
>
> $$\widehat{p\ } \pm 2*SE =$$

## Conclusions Based Off of Confidence Intervals

Recall the general interpretation of a confidence interval.

- We are 95% confident that the long run proportion of *"context"* falls between (*lower limit*) and (*upper limit*).

If the null hypothesis value is \_\_\_\_\_\_\_\_\_\_ of the interval

- It is a likely value

- Fail to Reject

If the null hypothesis value is \_\_\_\_\_\_\_\_\_\_\_ of the interval

- It is not a likely value

- Reject

Conclusion: We (do/do not) have evidence to conclude (restate alternative in context).

\newpage

In the context of the medical marijuana example,

- Hypothesis

  - $H_{O}:\pi = 0.5$

  - $H_{A}:\pi \neq 0.5$

- Confidence Interval

  - $(0.47,\ 0.55) \rightarrow Fail\ to\ Reject\ since\ 0.5\ falls\ inside\ our\ interval$

\

  ---------------------------------------------------------------------------------------------
                        
\

- Interpretation of Confidence Interval

  - We are 95% confident the long run proportion of adults in Minnesota who feel medical marijuana should be legalized falls between 0.47 and 0.55.

- Conclusion in context

  - We do not have evidence to conclude the long run proportion of adults in Minnesota who feel medical marijuana should be legalized is different from 0.5

## Conclusions

  ----------------------------------------------------------------------------------------------------------
                          **P-value**     **Standardized Statistic**         **Confidence Interval**
  -------------------- ----------------- ---------------------------- --------------------------------------
       **Reject**           \< 0.05           "Outside the 2's"        Hypothesized value outside of the CI

   **Fail to Reject**       \> 0.05           "Between the 2's"        Hypothesized value inside of the CI
  ----------------------------------------------------------------------------------------------------------

# Section 3.3: Confidence Intervals for Single Means

## Formula

The general formula for confidence intervals also applies to single means.



$$Observed\ Statistic\  \pm \ Multiplier\ *\ Standard\ Error$$

Before calculating the confidence interval, be sure that the validity conditions are met for the theory approach (sample size greater than 20 and the distribution is not strongly skewed).

The formula for the standard error is the same as from Chapter 2.



$$SE = \frac{s}{\sqrt{n}}$$

95% Confidence interval

$$\mathbf{CI =}\overline{\mathbf{x}}\mathbf{\pm 2*}\frac{\mathbf{s}}{\sqrt{\mathbf{n}}}\mathbf{= (Lower\ Limit,\ Upper\ Limit)}$$



## Example: Textbooks

Suppose that two Winona State University students gathered data on prices for a random sample of 30 textbooks from the campus bookstore. They found the average price was \$165.02 and the standard deviation was \$31.42. The data is plotted below.





Answer the following questions to get the confidence interval.

1)  What is the point estimate ($\overline{x}$)?

\

2)  What is the sample standard deviation (s)?

\

3)  Are the validity conditions met?

\



4)  Calculate the 95% confidence interval.


\
\
\


5)  Interpretation: We are \_\_\_\_\_ confident that the long-run \_\_\_\_\_\_\_\_\_\_ price of textbooks at Winona State University is between \_\_\_\_\_ and \_\_\_\_\_.

Let's explore what is meant by 95% confidence in this example. Check out the applet located at <https://twiedrw.shinyapps.io/confidence_intervals/>. Suppose we know that in the previous academic year that the population was normally distributed with an average textbook price of \$150 and a population standard deviation of \$35. Enter the information into the applet so that it looks like this:



(Note: ignore the limits on the mean and standard deviation in the applet)

# Section 3.4: Width of Confidence Intervals

## Factors Influencing the Confidence Interval

There are three factors that affect the width of a confidence interval: confidence level, sample size, and standard error.



## Confidence level

Significance Level + Confidence Level = \_\_\_\_\_\_\_

- Confidence Level Increases $\rightarrow$ Significance Level \_\_\_\_\_\_\_\_\_\_\_

  - Rejecting Less Often $\rightarrow$ More Likely Values

  - Interval Widens

- Confidence Level Decreases $\rightarrow$ Significance Level \_\_\_\_\_\_\_\_\_\_\_\_

  - Rejecting More Often $\rightarrow$ Fewer Likely Values

  - Interval Narrows

  - "If you want to be more confident you have to cover more values."

<!-- -->

- Hypothetical: what would a 100% confidence interval look like?

## Sample Size

Recall what happened when increasing the sample size on the applet in Section 3.3.

Larger sample size


\
\
\



Smaller sample size

\
\
\


Draw the relation between a large sample size and a small sample size.

+-------------------------------------+
| Large sample size                   |
|                                     |
|              |
+=====================================+
|              |
|                                     |
| Small sample size                   |
+-------------------------------------+



## Standard Error

General Formula

$$ Observed\ Statistic\  \pm \ Multiplier\ *\ Standard\ Error$$

What happens when the standard error increases? Decreases?


\newpage

## Technical Aside

Mathematically, why do the effects of sample size and standard error make sense? Recall the standard error formulas for both proportion and means below.


| | Standard Error |
|---|---|
| **One Proportion** | $SE = \sqrt{\frac{\widehat{p}(1-\widehat{p})}{n}}$ |
| **One Mean** | $SE = \frac{s}{\sqrt{n}}$ |

From the general formula for the confidence interval, we know that the sample size and standard error do not affect the observed statistic or the multiplier. As the sample size increases, the denominator of the standard error increases, which decreases the value for the standard error.

1)  What would happen if you took an infinitely large sample size?
