---
format: 
  pdf: 
    include-in-header:
      text: |
        \usepackage{fancyhdr}
        \pagestyle{fancy}
        \fancyhf{}
        \lhead{STAT 218}
        \chead{Chapter 3}
        \rhead{Fall 2026}
        \rfoot{\thepage}
        \setlength{\headheight}{14pt}
    fig-align: center
---

# Association and Confounding

## Definitions

Explanatory Variable (\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_, Predictor)

- Variable we think is "explaining" the change in the response variable

- In an experiment, this is what researchers \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_

Response Variable (Dependent)

- Variable that is being changed by the explanatory variable (i.e., the outcome)

Confounding Variable

- A variable that is related to both the explanatory and response variable in such a way that its effects cannot be \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ from the effects of the explanatory









## Example 1: Types of Variables

Suppose that a study is researching the effect of gasoline usage and miles driven in a car. Identify the following:

**Explanatory Variable:**

\
\
\

**Response Variable:**

\
\
\

**Potential Confounding Variables:**

\
\
\






## Your turn!

From the following scenarios, think about which variable is the explanatory and which one is the response. Also try to come up with some potential confounding variables

- Smoking and cancer

\
\
\

- Number of pets and size of home

\
\
\

- Money spent on groceries and number of people in household

\
\
\

- Amount of rainfall and river level

\
\
\


## Definitions (cont.)

Association: a relationship between two variables

- Information provided form one variable helps to \_\_\_\_\_\_\_\_\_\_\_\_\_\_ another variable.

Causal Connection: a cause-and-effect relationship between variables

- One variable has a \_\_\_\_\_\_\_\_\_\_ influence on the response variable

Note: Association does NOT justify causation. ([www.tylervigen.com](http://www.tylervigen.com/))

## Example 2

Researchers found that countries that have more TV's per 1,000 people have a higher average lifespan. Identify the following:

- Explanatory variable:

\
\
\


- Categorical or quantitative:

\
\
\


- Response variable:

\
\
\


- Categorical or quantitative:

\
\
\

- Potential confounding variable(s):

\
\
\
\
\


# Observational Studies vs. Experiments

Motivation: How can we take a sample so that we can reduce the risk of having confounding variables? Confounding variables add bias into a study, but there are ways to deal with this.

## Observational Studies

The groups that you wish to compare are "just there." Data is observed and collected on subjects without intervention of the results.

Examples: customer review surveys, teacher evaluations, smokers vs nonsmokers and lung cancer, etc.

## Experiments

You create the groups by what you choose to do to the people or the experimental units by assigning the conditions (i.e., \_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ of groups)

Examples:

- Assigning two diets to two different groups, then measuring the weight loss on each group

- Assigning students to listen to either classical music or country music before an exam, then comparing the group scores

## Randomized Experiments

Experiments can be designed in such a way that we can balance out confounding variables. This is done through random assignment into different treatment groups. For randomized experiments, this means that each subject/participant is randomly placed into a group. When conducting an experiment, our observational units are now called **experimental units.** (Technical note: an experimental unit, by definition, is the smallest entity to which randomization can occur.)

## What Type of Study to Use?

Consider the scenario of a researcher wanting to answer this research question: "Does exercise help prevent against colds and flus?"

- How can we make this an experimental study?

\
\
\
\
\


- How can we make this an observational study?

\
\
\
\
\




\newpage















## Random Sampling vs. Random Assignment

**Random Sampling:** representative sample from population so we can extend conclusion to the larger population.

- When random sampling is present, we can generalize the results to the population of interest.

- When random sampling is not present, we cannot generalize results to the population of interest.

Example: Suppose that a study wants to estimate the average weight of the Western Meadowlark (state bird of Nebraska). Researchers get samples from random areas in the state of Nebraska. Can we generalize the average weight to all Western Meadowlarks? To where can we generalize the results?

\
\
\
\
\


**Random Assignment:** produce similar groups so we can say that there is a cause-and-effect (causal) relationship between explanatory and response variables.

- When random assignment is present, we can determine causation because the study "balances out" potential confounding variables.

- When random assignment is not present, we cannot determine causation (only association). The confounding variables add bias into the results

  - Note: This is common with observational studies.

## Claims from Study Types

The following table summarizes what types of claims you can make depending on the type of study. We will not be focusing on how to write conclusions for each situation, but you should pay attention to how a study is designed and its implications.

  -------------------------------------------------------------------------------------------------------------------------------------------------------------
                                               **Association**                                             **Causal Connection**
  ------------------------------- ------------------------------------------ ----------------------------------------------------------------------------------
   **Subjects within the study**            Calculated statistics                                Experimental study with random assignment

          **Population**           Observational study with a random sample   Experimental study with random assignment [AND]{.underline} from a random sample
  -------------------------------------------------------------------------------------------------------------------------------------------------------------

# Example Problems

A study finds that larger cities have more traffic stops than smaller cities per 1,000 people. Identify the following:

- Observational or experimental:

\
\
\


- Explanatory variable:

\
\
\


- Response variable:

\
\
\

- Randomness:

\
\
\

- Potential confounding variables:

\newpage

Researchers randomly assigned two drugs, A and B, to two groups of volunteers. They found that Drug A performed better than Drug B.

- Observational or experimental:

\
\
\

- Explanatory variable:

\
\
\

- Response variable:

\
\
\

- Randomness:

\
\
\

- Potential confounding variables:




