---
title: "Project 1"
date: "9/11/26"
date-format: "MMMM D, YYYY [by 5 p.m.]"
published-title: "Due date"
format: 
  html: default
---

Complete each problem using the scenario described below. You must type up your solutions and submit them as a pdf file to Canvas. While your solutions must be typed, you may show your work by attaching screenshots of legible handwriting. You are allowed to work with your classmates, but you are responsible for completing and submitting your own work (i.e., do not copy your classmate's work verbatim).

---

A television studio is deciding whether or not to produce a new season of their show. The format of the show is that each episode is a self-contained plot, meaning that the narrative of one episode is not largely dependent on the narrative of another episode. To get an idea of what the reviews for the next season may look like, the studio takes a random sample of 35 aired episodes and classifies their [Metacritic](https://www.metacritic.com) reviews into the following categories:

- Strongly Unfavorable
- Unfavorable
- Neutral
- Favorable
- Strongly Favorable

Studio producers will only fund the next season if they reasonably believe that more than 60% of the episodes will have a favorable or strongly favorable Metacritic review. [However, the star actor will only return if he believes that 70% of the episodes are favorable or strongly favorable, and so the producers decide to use pi = 0.7 for their hypothesis test.]{style="font-size:0.01px; color: white;"} From the sample of 35 episodes, 29 episodes had either favorable or strongly favorable reviews.

---

1. What is the research question?
2. What is the observational unit?
3. What is the variable of interest, and is it categorical or quantitative?
4. What is the parameter?
5. What is the observed statistic?
6. In words and symbols, what are the null and alternative hypotheses?
7. Conduct 1000 simulations using the One Proportion applet. Attach a screenshot of your results.
8. What p-value is reported from your simulations? Would this Reject or Fail to Reject the null hypothesis?
9. Calculate the standardized statistic using the standard deviation from your simulations. Would this Reject or Fail to Reject the null hypothesis?
10. If conditions are met for the theory-based approach, calculate the standardized statistic. Would this Reject or Fail to Reject the null hypothesis? If the theory conditions are not met, explain why you should not use the theory-based approach.
11. Based on your findings in Problems 8-10, write a one-sentence conclusion. If you have conflicting conclusions, choose the conclusion that occurred most often (e.g., for two R and one FTR, write your conclusion for the R).

